In [1]:
import pandas as pd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pylab
import math
from scipy import stats
from sklearn import preprocessing
import statsmodels.api as sm
from statsmodels.stats import diagnostic as diag
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn import metrics

%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
from scipy.io import loadmat
import os
from scipy.optimize import fmin_cg
import scipy.io
import scipy.io as si

In [2]:
#Stack arrays in sequence horizontally (column wise).
np.hstack

<function numpy.hstack(tup)>

In [3]:
#Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye

<function numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')>

In [4]:
# np.roll Roll (move in a particular direction) array elements along a given axis.
np.roll

<function numpy.roll(a, shift, axis=None)>

# Index selection from numpy

In [5]:
y =np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [6]:
y[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [7]:
y[:2,:3]

array([[0, 1, 2],
       [7, 8, 9]])

In [8]:
y[:,:3]

array([[ 0,  1,  2],
       [ 7,  8,  9],
       [14, 15, 16],
       [21, 22, 23],
       [28, 29, 30]])

In [9]:
y[:,2:3]

array([[ 2],
       [ 9],
       [16],
       [23],
       [30]])

In [10]:
#size inja 5*1
y[:,6:7]

array([[ 6],
       [13],
       [20],
       [27],
       [34]])

In [11]:
#size array ba balai fargh dare, 1*5
y[:,6]

array([ 6, 13, 20, 27, 34])


# Index selection from pandas

In [12]:
 dates = pd.date_range('1/1/2000', periods=8)

In [13]:
df = pd.DataFrame(np.random.randn(8, 4),index=dates, columns=['A', 'B', 'C', 'D'])

In [14]:
df

A         B         C         D
2000-01-01 -1.684100  0.949063  1.567990 -0.079819
2000-01-02 -0.379168 -0.630180 -1.043777  1.778574
2000-01-03 -0.850196  0.482828  0.223072  0.630910
2000-01-04  1.111303 -1.426620 -1.211976  0.475289
2000-01-05  0.794173  1.308347 -0.405706  0.455019
2000-01-06  0.967509  1.290951  0.642981  0.190391
2000-01-07  0.327321 -0.317337 -0.611482  0.357551
2000-01-08  0.032031  0.041630 -0.549961 -0.334102

In [15]:
#age esm column nayad fagaht satr manzur has
df[:3]

A         B         C         D
2000-01-01 -1.684100  0.949063  1.567990 -0.079819
2000-01-02 -0.379168 -0.630180 -1.043777  1.778574
2000-01-03 -0.850196  0.482828  0.223072  0.630910

In [16]:
#vaghti :: miad yani tarz entekhab kardan
df[::2]

A         B         C         D
2000-01-01 -1.684100  0.949063  1.567990 -0.079819
2000-01-03 -0.850196  0.482828  0.223072  0.630910
2000-01-05  0.794173  1.308347 -0.405706  0.455019
2000-01-07  0.327321 -0.317337 -0.611482  0.357551

In [17]:
 df['A'][1:3]

2000-01-02   -0.379168
2000-01-03   -0.850196
Freq: D, Name: A, dtype: float64

In [18]:
df['A'][:5]

2000-01-01   -1.684100
2000-01-02   -0.379168
2000-01-03   -0.850196
2000-01-04    1.111303
2000-01-05    0.794173
Freq: D, Name: A, dtype: float64

In [19]:
df[::-1]

A         B         C         D
2000-01-08  0.032031  0.041630 -0.549961 -0.334102
2000-01-07  0.327321 -0.317337 -0.611482  0.357551
2000-01-06  0.967509  1.290951  0.642981  0.190391
2000-01-05  0.794173  1.308347 -0.405706  0.455019
2000-01-04  1.111303 -1.426620 -1.211976  0.475289
2000-01-03 -0.850196  0.482828  0.223072  0.630910
2000-01-02 -0.379168 -0.630180 -1.043777  1.778574
2000-01-01 -1.684100  0.949063  1.567990 -0.079819

# Resize numpy arange

In [20]:
a=np.arange(-100,100,0.1)
y=np.resize(a,(569))
y.shape

(569,)

# Assign empty list
### create an empty list and append items to it

In [21]:
#with append
sample_list = []
for i in range(10):
    sample_list.append(i)

In [22]:
sample_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
num = []
for i in range(3, 15, 2):
    num.append(i)
num

[3, 5, 7, 9, 11, 13]

In [24]:
#or with insert
sample_list = []
for i in range(10):
    sample_list.insert(len(sample_list), i)
sample_list 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Assign empty array
### create an empty array and append items to it

In [25]:
sample= np.array([])
for n in  np.arange(5):
    value = (n + 1)*3
    sample = np.append(sample , value)

In [26]:
sample

array([ 3.,  6.,  9., 12., 15.])

==========================================
# What does *args and **kwargs do in the function definition
### *args and **kwargs allow you to pass multiple arguments or keyword arguments to a function. 

In [27]:
def my_sum(a, b):
    return a + b

### This function works fine, but it’s limited to only two arguments. What if you need to sum a varying number of arguments

### *kwargs works just like *args instead of accepting positional arguments it accepts keyword (or named) arguments. 

In [28]:
def concatenate(**kwargs):
    result = ""
    # Iterating over the Python kwargs dictionary
    for arg in kwargs.values():
        result += arg
    return result

print(concatenate(a="Real", b="Python", c="Is", d="Great", e="!"))

RealPythonIsGreat!


In [29]:
def drawLine(p1, p2, *args, **kwargs):
    
    plt.plot([p1[0], p2[0]], [p1[1], p2[1]], *args, **kwargs)

# Dimentionality Reduction
### np.linalg.svd is finding eigenvector and eighenvalues of a matrix (hear we look for eigenvallues and eigenvector of covariance matrix of the data). The bigger eigenvalue which lead to bigger eigenvector is our PCA.


In [30]:
# u is one eigenvector and v is the second. but we choose the biger one for PCA
#u, s, v = np.linalg.svd()
#u,s = pca(X_norm)

### There are differetn ways to find eigenvalues and vector in python:

In [31]:
Cov =np.array([[1.8,1.2],[4.4,4.6]])

In [32]:
values,vectors=np.linalg.eig(Cov.T*Cov)
vectors

array([[-0.96476382, -0.26311741],
       [ 0.26311741, -0.96476382]])

In [33]:
values

array([ 1.8, 22.6])

remeber that the eigenvector and values from the latter might be different in rows or columns. better to go with svd

### example 2, the result are correct (taken from exersize). the give same result but row and columsn are different and should be taken care of.

In [34]:
C = np.matrix([[5,5],[-1,7]])
C

matrix([[ 5,  5],
        [-1,  7]])

In [35]:
#should be normalized 
C.T*C

matrix([[26, 18],
        [18, 74]])

In [36]:
w, v = np.linalg.eig(C.T*C)
v

matrix([[-0.9486833 , -0.31622777],
        [ 0.31622777, -0.9486833 ]])

In [37]:
w

array([20., 80.])

In [38]:
u, s, vh = np.linalg.svd(C)
vh

matrix([[ 0.31622777,  0.9486833 ],
        [ 0.9486833 , -0.31622777]])

In [39]:
u

matrix([[ 0.70710678,  0.70710678],
        [ 0.70710678, -0.70710678]])

In [40]:
s**2

array([80., 20.])

# pass statement
#### The pass statement is used as a placeholder for future code. When the pass statement is executed, nothing happens, but you avoid getting an error when empty code is not allowed.

In [41]:
# when it reaches 'h' does not do anything
for letter in 'Python': 
   if letter == 'h':
      pass
      print('This is pass block')
   print('Current Letter :', letter)

print("Good bye!")

Current Letter : P
Current Letter : y
Current Letter : t
This is pass block
Current Letter : h
Current Letter : o
Current Letter : n
Good bye!


# Print

In [42]:
name ='giacomo'
number = 4.3
print('%s %s' % (name, number))

giacomo 4.3


In [43]:
name ='giacomo'
number = 4.3
print('number {}'.format(name)) 

number giacomo


# Some more

In [44]:
len('Hello World')

11

In [45]:
s='hello world'
s[0]

'h'

In [46]:
s[:]

'hello world'

In [47]:
s[::2]

'hlowrd'

In [48]:
s.split()

['hello', 'world']

In [49]:
s.split()[1]

'world'

In [50]:
s + ' concatenate me!'

'hello world concatenate me!'

In [51]:
my_list = ['one','two','three',4,5]

In [52]:
my_list + ['new item']

['one', 'two', 'three', 4, 5, 'new item']

In [53]:
list1 = [1,2,3]

In [54]:
# append is in-place for list, meaning that it does not return asigned name but the initual name, here list1
# nokte: inja nemituni be paini assign koni chizi, dobare bayad list1 ro seda koni
list1.append('append me!')
list1

[1, 2, 3, 'append me!']

In [55]:
#extend is in-place
x = [1, 2, 3]
y = [4, 5, 6]
x.extend(y)
print(x)

[1, 2, 3, 4, 5, 6]


In [56]:
mylist = ['a', 'b', 'b', 'c']
mylist.index('b')

1

In [57]:
mylist.index('c')

3

In [58]:
matrix=[[6, 2, 3], [4, 5, 6], [7, 8, 9]]

In [59]:
matrix[0][0]

6

# Input

In [60]:
# get input from user

inputString = input()

print('The inputted string is:', inputString)

1
The inputted string is: 1


In [61]:
# get input from user

inputString = input('Enter a string:')

print('The inputted string is:', inputString)

Enter a string:2
The inputted string is: 2


In [62]:
 input('go one')

go one


''

# Dictionary

In [63]:
my_dict = {'key1':'value1','key2':'value2'}

In [64]:

my_dict['key2']

'value2'

In [65]:
my_dict1 = {'key1':123,'key2':[12,23,33],'key3':['item0','item1','item2']}

In [66]:
my_dict1['key3']

['item0', 'item1', 'item2']

In [67]:
my_dict1['key3'][0]

'item0'

In [68]:
my_dict1['key1'] = my_dict1['key1'] - 123

In [69]:
my_dict1['key1']

0

# Tuple

In [70]:
t = ('one',2)

In [71]:
t[0]

'one'

In [72]:
t[-1]

2

# Set
### collection of unique elements

In [73]:
list1 = [1,1,2,2,3,4,5,6,1,1,10]

In [74]:
set(list1)

{1, 2, 3, 4, 5, 6, 10}

In [75]:
x = set()

In [76]:
x.add(1)

In [77]:
x

{1}

In [78]:
x.add(2)

In [79]:
x

{1, 2}

In [80]:
list5 = [1,2,2,33,4,4,11,22,3,3,2]

In [81]:
x = set(list5 )

In [82]:
x

{1, 2, 3, 4, 11, 22, 33}

# For loop

In [83]:
st = 'Print only the words that start with s in this sentence'

In [84]:
for i in st.split():
    if i[0] == 's':
        print(i)

start
s
sentence


In [85]:
list(range(0,11,2))

[0, 2, 4, 6, 8, 10]

### Write a program that prints the integers from 1 to 100. But for multiples of three print "Fizz" instead of the number, and for the multiples of five print "Buzz". For numbers which are multiples of both three and five print "FizzBuzz".

In [86]:
for num in range(1,16):
    if num % 3 == 0 and num % 5 == 0:
        print("FizzBuzz")
    elif num % 3 == 0:
        print("Fizz")
    elif num % 5 == 0:
        print("Buzz")
    else:
        print(num)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz


# If

In [87]:
loc = 'Bank'

if loc == 'Auto Shop':
    print('Welcome to the Auto Shop!')
elif loc == 'Bank':
    print('Welcome to the bank!')
else:
    print('Where are you?')

Welcome to the bank!


### print only the even numbers from this list, if not print 'odd number'

In [88]:
list1 = [1,2,3,4,5,6,7,8,9,10]

In [89]:
for num in list1:
    if num % 2 == 0:
        print(num)
    else:
        print('Odd number')

Odd number
2
Odd number
4
Odd number
6
Odd number
8
Odd number
10


# while

In [90]:
x = 0

while x < 5:
    print('x is currently: ',x)
    print(' x is still less than 10, adding 1 to x')
    x+=1

x is currently:  0
 x is still less than 10, adding 1 to x
x is currently:  1
 x is still less than 10, adding 1 to x
x is currently:  2
 x is still less than 10, adding 1 to x
x is currently:  3
 x is still less than 10, adding 1 to x
x is currently:  4
 x is still less than 10, adding 1 to x


In [91]:
x = 0

while x < 5:
    print('x is currently: ',x)
    print(' x is still less than 10, adding 1 to x')
    x+=1
    if x==3:
        print('x==3')
    else:
        print('continuing...')
        continue

x is currently:  0
 x is still less than 10, adding 1 to x
continuing...
x is currently:  1
 x is still less than 10, adding 1 to x
continuing...
x is currently:  2
 x is still less than 10, adding 1 to x
x==3
x is currently:  3
 x is still less than 10, adding 1 to x
continuing...
x is currently:  4
 x is still less than 10, adding 1 to x
continuing...


In [92]:
x = 0

while x < 10:
    print('x is currently: ',x)
    print(' x is still less than 10, adding 1 to x')
    x+=1
    if x==3:
        print('Breaking because x==3')
        break
    else:
        print('continuing...')
        continue

x is currently:  0
 x is still less than 10, adding 1 to x
continuing...
x is currently:  1
 x is still less than 10, adding 1 to x
continuing...
x is currently:  2
 x is still less than 10, adding 1 to x
Breaking because x==3


# Function interactions

In [93]:
example=[1,5,4]

In [94]:
from random import shuffle

In [95]:
#it is in-place,it does not return 'result' but the intial name which is example
result=shuffle(example)

In [96]:
example

[5, 1, 4]

In [97]:
# vali ba tarif function mitunim hala ye esmi assign konim be shuffle.
def shuffle_l(mylist):
    shuffle(mylist)
    return mylist

In [98]:
g=shuffle_l(example)
g

[1, 5, 4]

In [99]:
# game list looks like:user guess where is 'o'
mylist=[' ', 'o', ' ']

In [100]:
shuffle_l(mylist)

[' ', ' ', 'o']

In [101]:
# below why 0,1,2 are written as string, becuase input always returns string
def player_guess():
    guess=''
    
    while guess not in ['0','1','2']:
        guess=input('pick a number :0,1 or 2')
    return int(guess)
    
    

In [122]:
player_guess()

pick a number :0,1 or 22


2

In [123]:
#below is interaction betwee two latter functions
def check_guess(mylist, guess):
    if mylist[guess]== 'o':
        print('correct')
    else:
        print('wrong guess')

In [124]:
mylist=['','o','']
guess=player_guess()
check_guess(mylist, guess)

pick a number :0,1 or 23
pick a number :0,1 or 22
wrong guess


# Functions

### Write a function that returns the lesser of two given numbers if both numbers are even, but returns the greater if one or both numbers are odd

In [125]:
def lesser_of_two_evens(a,b):
    if a%2 == 0 and b%2 == 0:
        return min(a,b)
    else:
        return max(a,b)

In [126]:
lesser_of_two_evens(2,4)

2

### Write a function takes a two-word string and returns True if both words begin with same letter

In [127]:
def animal_crackers(text):
    wordlist = text.split()
    return wordlist[0][0] == wordlist[1][0]

In [128]:
animal_crackers('Levelheaded Llama')

True

### Given a list of ints, return True if the array contains a 3 next to a 3 somewehe

In [129]:
#method 1. Note the place of last return, it does not inside the for loop. so the for loops finishes over all i then goes to the last return.
def f(num):
    for i in range(0,len(num)-1):
        if num[i]==3 and num[i+1]==3:
            return True
    
    return False

In [130]:
f([1,3,5,3,3])

True

In [131]:
len([1,3,5,3,3])-1

4

In [132]:
#method 2
def f(num):
    for i in range(0,len(num)-1):
        if num[i:i+2]==[3,3]:
            return True
    return False

In [133]:
f([1,3,5,3])

False

### given a string, return a string where for every charachter in the original there are three character, e.g. Hello ---> HHHeeellllllooo

In [134]:
import numpy as np
def D(text):
    t=''
    for i in range(0,len(text)):
        t+=text[i]*3
    return t

In [135]:
D('text')

'ttteeexxxttt'

In [136]:
t=('tk')
t[1]*3

'kkk'

In [137]:
# note: .append does not work for strings, instead always try this
t=''
t += "lwrewr" 
t

'lwrewr'

### given three integers between 1 and 11, if their sum is less that or equl to 21, return their sum. If therie sum exceeds 21 and there is an eleven, redunce the total sum by 10. Finally if the sum (even after adjusment) excees 21, retunr 'BUST

In [138]:
#method1
def f(a,b,c):
    g=(a,b,c)
    if sum(g) <= 21:
        return sum(g)
    if sum(g) > 21 and b==11 or a==11 or c==11:
        return sum(g)-10
    if sum(g) > 21:
        return 'BUST'

In [139]:
f(15,9,6)


'BUST'

In [146]:
#method1
def f(a,b,c):
    if sum([a,b,c]) <= 21:
        return sum([a,b,c])
    elif sum([a,b,c])  > 21 and b==11 or a==11 or c==11:
        return sum([a,b,c])-10
    else:
        sum([a,b,c])  > 21
        return 'BUST'

In [147]:
f(15,9,6)

'BUST'

In [150]:
# note the first one does not work, should do the second
#sum(a,b,c)
#sum([a,b,c])

In [151]:
g=(5,6,7)
sum([5,6,7])

18

### return the sum of the numbers in the array, except ignore sections of numbers starting with a 6 and extending to the next 9 (every 6 will be followed by at least one 9). Return 0 for no numbers.

In [152]:
def f(num):
    sum=0
    for i in range(0,len(num)):
        sum += num[i]
    return sum

In [153]:
f([5,6,9])

20

In [154]:
###AGAIN, note to the last RETURN how it is written. we do no have else 
def f(num):
    for i in range(0,len(num)):
        for j in range(i+1,len(num)):
            if num[i]==6 and num[j]==9:
                d=num.index(6)
                h=num[:d]
                return sum(h)
    return sum(num)

In [155]:
f([12,2,6,9,11])


14

In [156]:
f=[5,6,9]

In [157]:
f.index(6)

1

In [158]:
sum(f[1:3])

15

In [159]:
g=[5,6,9]
g.index(6)

1

### Write a function that takes in a list of integers and returns true if it contains 007 in order


In [160]:
def f(num):
    for i in  range(0,len(num)):
        if num[i]==0 and num[i+1]==0 and num[i+2]==7:
            return True
    return False

In [161]:
f([12,0,6,0,7])

False

In [162]:
f([12,2,0,0,7])

True

## Join

In [163]:
list=['a','c','v']

In [164]:
''.join(list)

'acv'

In [165]:
'  '.join(list)

'a  c  v'